# Generated by Django 5.2.7 on 2025-10-14 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='produto',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 1, 48, 22, 99594, tzinfo=datetime.timezone.utc), verbose_name='data de emissão do produto'),
            preserve_default=False,
        ),
    ]
