# Generated by Django 5.2.7 on 2025-10-14 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_categoria_pub_date_produto_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de emissão do produto'),
        ),
    ]
